name: SKGuard
version: 1.0-SNAPSHOT
main: com.skguard.SKGuard
api-version: 1.20
authors: [Hector]
description: Advanced Security Plugin 1.20+
website: www.soulcraft.com

commands:
  skguard:
    description: Main command for SKGuard
    usage: /skguard <reload|help|audit|maintenance>
    aliases: [skg]
  pin:
    description: Enter or set your staff PIN
    usage: /pin <number> OR /pin set <number>
  report:
    description: Report a player for suspicious activity
    usage: /report <player> <reason>
  login:
    description: Log in to your account
    usage: /login <password>
    aliases: [l]
  register:
    description: Create a new account
    usage: /register <password> <confirm_password>
    aliases: [reg]
  2fa:
    description: Setup or verify your 2FA token
    usage: /2fa <setup|confirm|verify> <code>

permissions:
  skguard.admin:
    description: Allows full access to SKGuard
    default: op
  skguard.staff:
    description: Basic staff permission for PIN system
    default: false
  skguard.bypass.exploit:
    description: Bypass illegal item checks
    default: false
  skguard.bypass.movement:
    description: Bypass movement verification
    default: false
  skguard.bypass.afk:
    description: Bypass AFK kick
    default: false

